<?php

declare(strict_types=1);

namespace App\Baas\Runtime;

use App\Baas\Security\InputSanitizer;
use Doctrine\DBAL\Connection;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * Guarded DDL gateway for admin-only BaaS schema operations.
 * It deliberately supports a small SQL type allow-list and strict identifiers.
 */
final class SchemaOperationGateway
{
    private const TYPE_MAP = [
        'id' => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        'int' => 'INTEGER',
        'bigint' => 'BIGINT',
        'smallint' => 'SMALLINT',
        'float' => 'DOUBLE PRECISION',
        'decimal' => 'NUMERIC(18,2)',
        'bool' => 'BOOLEAN',
        'string' => 'VARCHAR(255)',
        'text' => 'TEXT',
        'json' => 'JSONB',
        'datetime_immutable' => 'TIMESTAMP(0) WITHOUT TIME ZONE',
        'date' => 'DATE',
        'time' => 'TIME',
        'uuid' => 'UUID',
        'email' => 'VARCHAR(255)',
        'url' => 'VARCHAR(2048)',
    ];

    public function __construct(
        private readonly Connection $connection,
        private readonly InputSanitizer $sanitizer,
    ) {
    }

    /** @return list<array<string,mixed>> */
    public function tables(): array
    {
        return $this->connection->fetchAllAssociative(<<<'SQL'
            SELECT table_name AS name
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
            ORDER BY table_name
        SQL);
    }

    /** @return list<array<string,mixed>> */
    public function columns(string $table): array
    {
        $this->assertName($table, 'table');

        return $this->connection->fetchAllAssociative(<<<'SQL'
            SELECT column_name AS name, data_type AS type, is_nullable AS nullable, column_default AS default
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = :table
            ORDER BY ordinal_position
        SQL, ['table' => $table]);
    }

    /** @param list<array<string,mixed>> $columns */
    public function createTable(string $table, array $columns): void
    {
        $table = $this->assertName($table, 'table');
        if ($columns === []) {
            $columns = [['name' => 'id', 'type' => 'id']];
        }

        $definitions = [];
        foreach ($columns as $column) {
            if (!\is_array($column)) {
                throw new BadRequestHttpException('Column definition must be an object.');
            }
            $definitions[] = $this->columnDefinition($column);
        }

        $sql = sprintf('CREATE TABLE %s (%s)', $this->q($table), implode(', ', $definitions));
        $this->connection->executeStatement($sql);
    }

    public function renameTable(string $table, string $newName): void
    {
        $table = $this->assertName($table, 'table');
        $newName = $this->assertName($newName, 'new table');
        $this->connection->executeStatement(sprintf('ALTER TABLE %s RENAME TO %s', $this->q($table), $this->q($newName)));
    }

    public function dropTable(string $table): void
    {
        $table = $this->assertName($table, 'table');
        $this->connection->executeStatement(sprintf('DROP TABLE %s', $this->q($table)));
    }

    /** @param array<string,mixed> $definition */
    public function addColumn(string $table, array $definition): void
    {
        $table = $this->assertName($table, 'table');
        $this->connection->executeStatement(sprintf('ALTER TABLE %s ADD COLUMN %s', $this->q($table), $this->columnDefinition($definition)));
    }

    /** @param array<string,mixed> $set */
    public function alterColumn(string $table, string $column, array $set): void
    {
        $table = $this->assertName($table, 'table');
        $column = $this->assertName($column, 'column');

        if (isset($set['name'])) {
            $newName = $this->assertName((string) $set['name'], 'new column');
            $this->connection->executeStatement(sprintf('ALTER TABLE %s RENAME COLUMN %s TO %s', $this->q($table), $this->q($column), $this->q($newName)));
            $column = $newName;
        }

        if (isset($set['type'])) {
            $type = $this->sqlType((string) $set['type'], $set);
            $this->connection->executeStatement(sprintf('ALTER TABLE %s ALTER COLUMN %s TYPE %s', $this->q($table), $this->q($column), $type));
        }

        if (array_key_exists('nullable', $set)) {
            $action = filter_var($set['nullable'], FILTER_VALIDATE_BOOL) ? 'DROP NOT NULL' : 'SET NOT NULL';
            $this->connection->executeStatement(sprintf('ALTER TABLE %s ALTER COLUMN %s %s', $this->q($table), $this->q($column), $action));
        }
    }

    public function dropColumn(string $table, string $column): void
    {
        $table = $this->assertName($table, 'table');
        $column = $this->assertName($column, 'column');
        if ($column === 'id') {
            throw new BadRequestHttpException('The primary id column cannot be dropped.');
        }

        $this->connection->executeStatement(sprintf('ALTER TABLE %s DROP COLUMN %s', $this->q($table), $this->q($column)));
    }

    /** @param array<string,mixed> $definition */
    private function columnDefinition(array $definition): string
    {
        $name = $this->assertName((string) ($definition['name'] ?? ''), 'column');
        $type = $this->sqlType((string) ($definition['type'] ?? 'string'), $definition);
        $nullable = ($definition['nullable'] ?? false) ? '' : ' NOT NULL';
        if (($definition['type'] ?? null) === 'id') {
            $nullable = '';
        }

        return sprintf('%s %s%s', $this->q($name), $type, $nullable);
    }

    /** @param array<string,mixed> $options */
    private function sqlType(string $type, array $options): string
    {
        if (!isset(self::TYPE_MAP[$type])) {
            throw new BadRequestHttpException(sprintf('Unsupported SQL type "%s".', $type));
        }

        if ($type === 'string' && isset($options['length'])) {
            $length = max(1, min(4096, (int) $options['length']));
            return sprintf('VARCHAR(%d)', $length);
        }

        return self::TYPE_MAP[$type];
    }

    private function assertName(string $name, string $label): string
    {
        return strtolower($this->sanitizer->assertIdentifier($name, $label));
    }

    private function q(string $identifier): string
    {
        return $this->connection->quoteIdentifier($identifier);
    }
}
