<?php

declare(strict_types=1);

namespace App\Command;

use App\Baas\Loader\ModelLoader;
use App\Baas\Model\Field;
use App\Baas\Model\Model;
use Doctrine\DBAL\Connection;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Synchronizes optional sandbox YAML model files directly to PostgreSQL tables.
 *
 * This is intentionally not a PHP class generator: the BaaS runtime introspects
 * the live database and can operate on any table created by this command or by
 * an external system.
 */
#[AsCommand(name: 'app:models:schema:sync', description: 'Synchronize YAML model definitions to PostgreSQL without generating PHP classes.')]
final class ModelsSchemaSyncCommand extends Command
{
    public function __construct(
        private readonly ModelLoader $loader,
        private readonly Connection $connection,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $models = array_values(array_filter($this->loader->loadAll(), fn (Model $model): bool => $model->isPostgres()));

        foreach ($models as $model) {
            $this->createTable($model);
            $io->writeln(sprintf('  - table %s synchronized', $model->table));
        }

        foreach ($models as $model) {
            $this->createRelations($model, $models);
        }

        $io->success(sprintf('Synchronized %d PostgreSQL model tables.', count($models)));

        return Command::SUCCESS;
    }

    private function createTable(Model $model): void
    {
        $this->assertIdentifier($model->table);
        $this->connection->executeStatement(sprintf(
            'CREATE TABLE IF NOT EXISTS %s (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)',
            $this->q($model->table),
        ));

        foreach ($model->fields as $field) {
            if ($field->isPrimary()) {
                continue;
            }
            $column = Model::toSnake($field->name);
            $this->assertIdentifier($column);
            if (!$this->columnExists($model->table, $column)) {
                $this->connection->executeStatement(sprintf(
                    'ALTER TABLE %s ADD COLUMN %s %s',
                    $this->q($model->table),
                    $this->q($column),
                    $this->columnDefinition($field),
                ));
            }
            if ($field->unique) {
                $this->ensureUniqueIndex($model->table, [$column], sprintf('uniq_%s_%s', $model->table, $column));
            }
        }
    }

    /** @param list<Model> $models */
    private function createRelations(Model $model, array $models): void
    {
        $byName = [];
        foreach ($models as $candidate) {
            $byName[$candidate->name] = $candidate;
        }

        foreach ($model->relations as $relation) {
            if (!$relation->isOwning() || !isset($byName[$relation->target])) {
                continue;
            }

            $column = Model::toSnake($relation->name) . '_id';
            $this->assertIdentifier($column);
            if (!$this->columnExists($model->table, $column)) {
                $this->connection->executeStatement(sprintf(
                    'ALTER TABLE %s ADD COLUMN %s INTEGER %s',
                    $this->q($model->table),
                    $this->q($column),
                    $relation->nullable ? 'NULL' : 'NOT NULL',
                ));
            }

            $target = $byName[$relation->target];
            $fk = sprintf('fk_%s_%s', $model->table, $column);
            if (!$this->foreignKeyExists($model->table, $fk)) {
                $onDelete = $relation->onDelete !== null ? ' ON DELETE ' . strtoupper($relation->onDelete) : '';
                $this->connection->executeStatement(sprintf(
                    'ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (id)%s',
                    $this->q($model->table),
                    $this->q($fk),
                    $this->q($column),
                    $this->q($target->table),
                    $onDelete,
                ));
            }
        }
    }

    private function columnDefinition(Field $field): string
    {
        $type = match ($field->type) {
            'string' => sprintf('VARCHAR(%d)', $field->length ?? 255),
            'text' => 'TEXT',
            'integer', 'int' => 'INTEGER',
            'float' => 'DOUBLE PRECISION',
            'decimal' => 'NUMERIC(12, 2)',
            'boolean', 'bool' => 'BOOLEAN',
            'datetime_immutable', 'datetime' => 'TIMESTAMP(0) WITHOUT TIME ZONE',
            'date' => 'DATE',
            'time' => 'TIME(0) WITHOUT TIME ZONE',
            'json' => 'JSONB',
            default => 'TEXT',
        };

        $nullable = $field->nullable ? 'NULL' : 'NOT NULL';
        $default = $field->default !== null ? ' DEFAULT ' . $this->defaultSql($field) : '';

        return $type . ' ' . $nullable . $default;
    }

    private function defaultSql(Field $field): string
    {
        $default = $field->default;
        if ($field->default === 'now' && $field->isDateTimeType()) {
            $default = 'CURRENT_TIMESTAMP';
        } elseif (is_bool($default)) {
            $default = $default ? 'TRUE' : 'FALSE';
        } elseif (is_int($default) || is_float($default)) {
            $default = (string) $default;
        } else {
            $default = $this->connection->quote((string) $default);
        }

        return $default;
    }

    /** @param list<string> $columns */
    private function ensureUniqueIndex(string $table, array $columns, string $name): void
    {
        $this->assertIdentifier($name);
        $exists = $this->connection->fetchOne(
            'SELECT 1 FROM pg_indexes WHERE schemaname = current_schema() AND tablename = :table AND indexname = :name',
            ['table' => $table, 'name' => $name],
        );
        if ($exists) {
            return;
        }

        $this->connection->executeStatement(sprintf(
            'CREATE UNIQUE INDEX %s ON %s (%s)',
            $this->q($name),
            $this->q($table),
            implode(', ', array_map(fn (string $column): string => $this->q($column), $columns)),
        ));
    }

    private function columnExists(string $table, string $column): bool
    {
        return (bool) $this->connection->fetchOne(
            'SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = :table AND column_name = :column',
            ['table' => $table, 'column' => $column],
        );
    }

    private function foreignKeyExists(string $table, string $name): bool
    {
        return (bool) $this->connection->fetchOne(
            'SELECT 1 FROM information_schema.table_constraints WHERE table_schema = current_schema() AND table_name = :table AND constraint_name = :name AND constraint_type = :type',
            ['table' => $table, 'name' => $name, 'type' => 'FOREIGN KEY'],
        );
    }

    private function q(string $identifier): string
    {
        $this->assertIdentifier($identifier);

        return $this->connection->quoteIdentifier($identifier);
    }

    private function assertIdentifier(string $identifier): void
    {
        if (!preg_match('/^[a-zA-Z_]\w*$/', $identifier)) {
            throw new \InvalidArgumentException(sprintf('Invalid SQL identifier "%s".', $identifier));
        }
    }
}
