<?php

declare(strict_types=1);

namespace App\Controller;

use App\Baas\Generated\MongoResourceRegistry;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * Generic CRUD controller for mongo-backed resources, replacing API Platform
 * which only services the Doctrine ORM side.
 *
 * Routing convention:  /api/mongo/<slug>  where <slug> matches the model's
 * `table` value (snake_case plural). The slug is resolved against
 * {@see MongoResourceRegistry} which is regenerated by `app:models:generate`.
 *
 * Query DSL (GET /api/mongo/{resource}):
 *   ?where[field]=value         exact-match filter (multiple allowed)
 *   ?sort=field    or ?sort=-field
 *   ?page=1&limit=30
 */
final class MongoApiController extends AbstractController
{
    public function __construct(
        private readonly DocumentManager $dm,
        private readonly NormalizerInterface $normalizer,
        private readonly ValidatorInterface $validator,
    ) {
    }

    #[Route('/api/mongo/{resource}', name: 'api_mongo_collection', methods: ['GET', 'POST'])]
    public function collection(string $resource, Request $request): Response
    {
        $class = $this->resolveClass($resource);

        if ($request->isMethod('POST')) {
            return $this->createOne($class, $request);
        }

        /** @var DocumentRepository $repo */
        $repo = $this->dm->getRepository($class);

        $where = $request->query->all('where');
        $sortRaw = (string) $request->query->get('sort', '');
        $page  = max(1, (int) $request->query->get('page', 1));
        $limit = min(200, max(1, (int) $request->query->get('limit', 30)));

        $criteria = is_array($where) ? $where : [];
        $orderBy = [];
        if ($sortRaw !== '') {
            if (str_starts_with($sortRaw, '-')) {
                $orderBy[substr($sortRaw, 1)] = 'desc';
            } else {
                $orderBy[$sortRaw] = 'asc';
            }
        }

        $items = $repo->findBy($criteria, $orderBy, $limit, ($page - 1) * $limit);
        $total = $this->countDocuments($class, $criteria);

        return new JsonResponse([
            'data'  => $this->normalize($items),
            'meta'  => ['page' => $page, 'limit' => $limit, 'total' => $total],
        ]);
    }

    #[Route('/api/mongo/{resource}/{id}', name: 'api_mongo_item', methods: ['GET', 'PUT', 'PATCH', 'DELETE'], requirements: ['id' => '[a-z0-9]+'])]
    public function item(string $resource, string $id, Request $request): Response
    {
        $class = $this->resolveClass($resource);
        $repo  = $this->dm->getRepository($class);
        $doc   = $repo->find($id);
        if ($doc === null) {
            return new JsonResponse(['error' => 'Not found.'], 404);
        }

        if ($request->isMethod('GET')) {
            return new JsonResponse($this->normalize($doc));
        }

        if ($request->isMethod('DELETE')) {
            $this->dm->remove($doc);
            $this->dm->flush();

            return new JsonResponse(null, 204);
        }

        $payload = $this->decode($request);
        $this->hydrate($doc, $payload);
        $errors = $this->validator->validate($doc);
        if (\count($errors) > 0) {
            return $this->validationErrorResponse($errors);
        }
        $this->dm->flush();

        return new JsonResponse($this->normalize($doc));
    }

    private function createOne(string $class, Request $request): Response
    {
        $payload = $this->decode($request);
        $doc = new $class();
        $this->hydrate($doc, $payload);
        $errors = $this->validator->validate($doc);
        if (\count($errors) > 0) {
            return $this->validationErrorResponse($errors);
        }
        $this->dm->persist($doc);
        $this->dm->flush();

        return new JsonResponse($this->normalize($doc), 201);
    }

    private function resolveClass(string $resource): string
    {
        $class = MongoResourceRegistry::classFor($resource);
        if ($class === null) {
            throw $this->createNotFoundException(\sprintf('Unknown mongo resource "%s".', $resource));
        }

        return $class;
    }

    /** @param array<string, mixed> $criteria */
    private function countDocuments(string $class, array $criteria): int
    {
        $qb = $this->dm->createQueryBuilder($class);
        foreach ($criteria as $field => $value) {
            $qb->field((string) $field)->equals($value);
        }

        return (int) $qb->count()->getQuery()->execute();
    }

    /** @return array<string, mixed> */
    private function decode(Request $request): array
    {
        $body = (string) $request->getContent();
        if ($body === '') {
            return [];
        }
        try {
            $data = json_decode($body, true, 32, \JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw $this->createNotFoundException('Invalid JSON body: ' . $e->getMessage());
        }

        return \is_array($data) ? $data : [];
    }

    /** @param array<string, mixed> $payload */
    private function hydrate(object $doc, array $payload): void
    {
        foreach ($payload as $key => $value) {
            $setter = 'set' . ucfirst($key);
            if (method_exists($doc, $setter)) {
                $doc->$setter($value);
            }
        }
    }

    private function normalize(mixed $value): mixed
    {
        return $this->normalizer->normalize($value, 'json');
    }

    private function validationErrorResponse(\Symfony\Component\Validator\ConstraintViolationListInterface $errors): JsonResponse
    {
        $out = [];
        foreach ($errors as $e) {
            $out[] = ['property' => $e->getPropertyPath(), 'message' => $e->getMessage()];
        }

        return new JsonResponse(['error' => 'Validation failed.', 'violations' => $out], 422);
    }
}
