<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426045146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(80) NOT NULL, position SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AF346682B36786B ON categories (title)');
        $this->addSql('CREATE TABLE dishes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, price_cents INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_584DD35D12469DE2 ON dishes (category_id)');
        $this->addSql('CREATE TABLE menus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, price_cents INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reservations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guests SMALLINT NOT NULL, reserved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, allergies TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DA239B1E7706E ON reservations (restaurant_id)');
        $this->addSql('CREATE INDEX idx_reservation_reserved_at ON reservations (reserved_at)');
        $this->addSql('CREATE TABLE restaurants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, city VARCHAR(80) NOT NULL, address VARCHAR(200) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, capacity INT NOT NULL, service_duration_minutes SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service_hours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, weekday SMALLINT NOT NULL, service_label VARCHAR(20) NOT NULL, opens_at TIME(0) WITHOUT TIME ZONE NOT NULL, closes_at TIME(0) WITHOUT TIME ZONE NOT NULL, max_guests INT NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2368506AB1E7706E ON service_hours (restaurant_id)');
        $this->addSql('CREATE INDEX idx_service_weekday ON service_hours (weekday, service_label)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(120) DEFAULT NULL, first_name VARCHAR(80) DEFAULT NULL, last_name VARCHAR(80) DEFAULT NULL, attributes JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE dishes ADD CONSTRAINT FK_584DD35D12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_hours ADD CONSTRAINT FK_2368506AB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dishes DROP CONSTRAINT FK_584DD35D12469DE2');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239B1E7706E');
        $this->addSql('ALTER TABLE service_hours DROP CONSTRAINT FK_2368506AB1E7706E');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE dishes');
        $this->addSql('DROP TABLE menus');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE restaurants');
        $this->addSql('DROP TABLE service_hours');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
