api_platform:
    title: BaaS API
    version: 1.0.0
    doctrine: true
    doctrine_mongodb_odm: false
    formats:
        jsonld: ['application/ld+json']
        json:   ['application/json']
        html:   ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
